PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>

INSERT {
    GRAPH <http://localhost:7200/repositories/polina>
    {
        ?newFarm a was:Farm.
    }.
} WHERE {
	BIND(IRI(CONCAT("http://localhost:7200/repositories/polina#farm-", strUUID())) AS ?newFarm)
}
