PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX hmas: <https://purl.org/hmas/>

SELECT ?tractor WHERE {
  GRAPH <http://localhost:7200/repositories/polina> {
    BIND (<http://localhost:7200/repositories/polina#farm-4fe8df7e-fe3d-426b-8fda-ee54b0b20615> as ?farm)
    ?farm a was:Farm.    
    ?farm hmas:contains ?tractor.
    ?tractor a was:Tractor.
  }
}