PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>

SELECT ?farm ?section WHERE {
  GRAPH <http://localhost:7200/repositories/polina> {
    ?farm a was:Farm.
    ?farm was:containsLandSection ?section.
    ?section a was:LandSection.
  }
}